// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-jMNmY47Y8r9kE30Vc7tKpsIhh-YpU0',
    appId: '1:254975640262:web:8a7d5045ed5123f1614dc7',
    messagingSenderId: '254975640262',
    projectId: 'pos-muzamil-2026',
    authDomain: 'pos-muzamil-2026.firebaseapp.com',
    storageBucket: 'pos-muzamil-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh5dV2TjOIvPsfiv0gAwRVvqxHuASq0wA',
    appId: '1:254975640262:android:1a30a29146779084614dc7',
    messagingSenderId: '254975640262',
    projectId: 'pos-muzamil-2026',
    storageBucket: 'pos-muzamil-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkKThGD6JYoKvnmZjq6xkjANU4mW64KVs',
    appId: '1:254975640262:ios:2d9ec3d09be9461d614dc7',
    messagingSenderId: '254975640262',
    projectId: 'pos-muzamil-2026',
    storageBucket: 'pos-muzamil-2026.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkKThGD6JYoKvnmZjq6xkjANU4mW64KVs',
    appId: '1:254975640262:ios:2d9ec3d09be9461d614dc7',
    messagingSenderId: '254975640262',
    projectId: 'pos-muzamil-2026',
    storageBucket: 'pos-muzamil-2026.firebasestorage.app',
    iosBundleId: 'com.example.posSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX-jMNmY47Y8r9kE30Vc7tKpsIhh-YpU0',
    appId: '1:254975640262:web:fdec4d09f2a6656b614dc7',
    messagingSenderId: '254975640262',
    projectId: 'pos-muzamil-2026',
    authDomain: 'pos-muzamil-2026.firebaseapp.com',
    storageBucket: 'pos-muzamil-2026.firebasestorage.app',
  );
}
